# Task1: Merging 12 months sale into single file

In [191]:
import pandas as pd
import os
files = [file for file in os.listdir('Pandas-Data-Science-Tasks-Master/SalesAnalysis/Sales_Data')]
df = pd.DataFrame()
for f in files:
    df_temp = pd.read_csv('Pandas-Data-Science-Tasks-Master/SalesAnalysis/Sales_Data/'+f)
    df = pd.concat([df,df_temp])
# dropNa
df.dropna(inplace=True)
index_toDrop = df[df['Order ID']=='Order ID'].index
df.drop(index=index_toDrop,inplace=True)
df.drop_duplicates(inplace=True)

In [192]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"

In [193]:
df.isnull().sum()

Order ID            0
Product             0
Quantity Ordered    0
Price Each          0
Order Date          0
Purchase Address    0
dtype: int64

In [194]:
df.shape

(182476, 6)

In [195]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 182476 entries, 0 to 11685
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          182476 non-null  object
 1   Product           182476 non-null  object
 2   Quantity Ordered  182476 non-null  object
 3   Price Each        182476 non-null  object
 4   Order Date        182476 non-null  object
 5   Purchase Address  182476 non-null  object
dtypes: object(6)
memory usage: 9.7+ MB

# Task 2: Data Type Check

In [196]:
df['Price Each'] = pd.to_numeric(df['Price Each'])
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [197]:
df['Quantity Ordered'] = pd.to_numeric(df['Quantity Ordered'])

# Task 3: Split Purchase Address and Preparing data for analysis

In [198]:
# df['post_id'] = df['Purchase Address'].str[-5:]
# df['State Address'] = df['']
df['State'] = df['Purchase Address'].str[-8:-6]
df['State'].value_counts()

CA    72947
NY    24428
TX    24247
MA    19542
GA    14598
WA    14468
OR     9835
ME     2411
Name: State, dtype: int64

In [199]:
df = df.sort_values('Order Date').reset_index(drop=True)
df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,State
0,147268,Wired Headphones,1,11.99,2019-01-01 03:07:00,"9 Lake St, New York City, NY 10001",NY
1,148041,USB-C Charging Cable,1,11.95,2019-01-01 03:40:00,"760 Church St, San Francisco, CA 94016",CA
2,149343,Apple Airpods Headphones,1,150.00,2019-01-01 04:56:00,"735 5th St, New York City, NY 10001",NY
3,149964,AAA Batteries (4-pack),1,2.99,2019-01-01 05:53:00,"75 Jackson St, Dallas, TX 75001",TX
4,149350,USB-C Charging Cable,2,11.95,2019-01-01 06:03:00,"943 2nd St, Atlanta, GA 30301",GA
...,...,...,...,...,...,...,...
182471,304165,AAA Batteries (4-pack),1,2.99,2020-01-01 04:13:00,"825 Adams St, Portland, OR 97035",OR
182472,299125,USB-C Charging Cable,1,11.95,2020-01-01 04:21:00,"754 Hickory St, New York City, NY 10001",NY
182473,305840,Bose SoundSport Headphones,1,99.99,2020-01-01 04:54:00,"784 River St, San Francisco, CA 94016",CA
182474,300519,Lightning Charging Cable,1,14.95,2020-01-01 05:13:00,"657 Spruce St, New York City, NY 10001",NY
182475,300519,Bose SoundSport Headphones,1,99.99,2020-01-01 05:13:00,"657 Spruce St, New York City, NY 10001",NY

In [200]:
def city_finding(text):
    idx = text.index('St,')
    idx += 4
    city = text[idx:]
    city = city[:city.index(',')]
    return city

In [201]:
txt = df["Purchase Address"][0]
df['City'] = df['Purchase Address'].apply(city_finding)
df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,State,City
0,147268,Wired Headphones,1,11.99,2019-01-01 03:07:00,"9 Lake St, New York City, NY 10001",NY,New York City
1,148041,USB-C Charging Cable,1,11.95,2019-01-01 03:40:00,"760 Church St, San Francisco, CA 94016",CA,San Francisco
2,149343,Apple Airpods Headphones,1,150.00,2019-01-01 04:56:00,"735 5th St, New York City, NY 10001",NY,New York City
3,149964,AAA Batteries (4-pack),1,2.99,2019-01-01 05:53:00,"75 Jackson St, Dallas, TX 75001",TX,Dallas
4,149350,USB-C Charging Cable,2,11.95,2019-01-01 06:03:00,"943 2nd St, Atlanta, GA 30301",GA,Atlanta
...,...,...,...,...,...,...,...,...
182471,304165,AAA Batteries (4-pack),1,2.99,2020-01-01 04:13:00,"825 Adams St, Portland, OR 97035",OR,Portland
182472,299125,USB-C Charging Cable,1,11.95,2020-01-01 04:21:00,"754 Hickory St, New York City, NY 10001",NY,New York City
182473,305840,Bose SoundSport Headphones,1,99.99,2020-01-01 04:54:00,"784 River St, San Francisco, CA 94016",CA,San Francisco
182474,300519,Lightning Charging Cable,1,14.95,2020-01-01 05:13:00,"657 Spruce St, New York City, NY 10001",NY,New York City
182475,300519,Bose SoundSport Headphones,1,99.99,2020-01-01 05:13:00,"657 Spruce St, New York City, NY 10001",NY,New York City

In [202]:
df['Street'] = pd.Series(map(lambda x: x[:x.index(',')],df['Purchase Address']))
df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,State,City,Street
0,147268,Wired Headphones,1,11.99,2019-01-01 03:07:00,"9 Lake St, New York City, NY 10001",NY,New York City,9 Lake St
1,148041,USB-C Charging Cable,1,11.95,2019-01-01 03:40:00,"760 Church St, San Francisco, CA 94016",CA,San Francisco,760 Church St
2,149343,Apple Airpods Headphones,1,150.00,2019-01-01 04:56:00,"735 5th St, New York City, NY 10001",NY,New York City,735 5th St
3,149964,AAA Batteries (4-pack),1,2.99,2019-01-01 05:53:00,"75 Jackson St, Dallas, TX 75001",TX,Dallas,75 Jackson St
4,149350,USB-C Charging Cable,2,11.95,2019-01-01 06:03:00,"943 2nd St, Atlanta, GA 30301",GA,Atlanta,943 2nd St
...,...,...,...,...,...,...,...,...,...
182471,304165,AAA Batteries (4-pack),1,2.99,2020-01-01 04:13:00,"825 Adams St, Portland, OR 97035",OR,Portland,825 Adams St
182472,299125,USB-C Charging Cable,1,11.95,2020-01-01 04:21:00,"754 Hickory St, New York City, NY 10001",NY,New York City,754 Hickory St
182473,305840,Bose SoundSport Headphones,1,99.99,2020-01-01 04:54:00,"784 River St, San Francisco, CA 94016",CA,San Francisco,784 River St
182474,300519,Lightning Charging Cable,1,14.95,2020-01-01 05:13:00,"657 Spruce St, New York City, NY 10001",NY,New York City,657 Spruce St
182475,300519,Bose SoundSport Headphones,1,99.99,2020-01-01 05:13:00,"657 Spruce St, New York City, NY 10001",NY,New York City,657 Spruce St

In [203]:
df['post_id'] = df['Purchase Address'].str[-5:]
df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,State,City,Street,post_id
0,147268,Wired Headphones,1,11.99,2019-01-01 03:07:00,"9 Lake St, New York City, NY 10001",NY,New York City,9 Lake St,10001
1,148041,USB-C Charging Cable,1,11.95,2019-01-01 03:40:00,"760 Church St, San Francisco, CA 94016",CA,San Francisco,760 Church St,94016
2,149343,Apple Airpods Headphones,1,150.00,2019-01-01 04:56:00,"735 5th St, New York City, NY 10001",NY,New York City,735 5th St,10001
3,149964,AAA Batteries (4-pack),1,2.99,2019-01-01 05:53:00,"75 Jackson St, Dallas, TX 75001",TX,Dallas,75 Jackson St,75001
4,149350,USB-C Charging Cable,2,11.95,2019-01-01 06:03:00,"943 2nd St, Atlanta, GA 30301",GA,Atlanta,943 2nd St,30301
...,...,...,...,...,...,...,...,...,...,...
182471,304165,AAA Batteries (4-pack),1,2.99,2020-01-01 04:13:00,"825 Adams St, Portland, OR 97035",OR,Portland,825 Adams St,97035
182472,299125,USB-C Charging Cable,1,11.95,2020-01-01 04:21:00,"754 Hickory St, New York City, NY 10001",NY,New York City,754 Hickory St,10001
182473,305840,Bose SoundSport Headphones,1,99.99,2020-01-01 04:54:00,"784 River St, San Francisco, CA 94016",CA,San Francisco,784 River St,94016
182474,300519,Lightning Charging Cable,1,14.95,2020-01-01 05:13:00,"657 Spruce St, New York City, NY 10001",NY,New York City,657 Spruce St,10001
182475,300519,Bose SoundSport Headphones,1,99.99,2020-01-01 05:13:00,"657 Spruce St, New York City, NY 10001",NY,New York City,657 Spruce St,10001

In [204]:
df.columns

Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address', 'State', 'City', 'Street', 'post_id'],
      dtype='object')

In [205]:
df = df[['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date','Street', 'City' ,'State', 'post_id',
       'Purchase Address' ]]

In [206]:
df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Street,City,State,post_id,Purchase Address
0,147268,Wired Headphones,1,11.99,2019-01-01 03:07:00,9 Lake St,New York City,NY,10001,"9 Lake St, New York City, NY 10001"
1,148041,USB-C Charging Cable,1,11.95,2019-01-01 03:40:00,760 Church St,San Francisco,CA,94016,"760 Church St, San Francisco, CA 94016"
2,149343,Apple Airpods Headphones,1,150.00,2019-01-01 04:56:00,735 5th St,New York City,NY,10001,"735 5th St, New York City, NY 10001"
3,149964,AAA Batteries (4-pack),1,2.99,2019-01-01 05:53:00,75 Jackson St,Dallas,TX,75001,"75 Jackson St, Dallas, TX 75001"
4,149350,USB-C Charging Cable,2,11.95,2019-01-01 06:03:00,943 2nd St,Atlanta,GA,30301,"943 2nd St, Atlanta, GA 30301"
...,...,...,...,...,...,...,...,...,...,...
182471,304165,AAA Batteries (4-pack),1,2.99,2020-01-01 04:13:00,825 Adams St,Portland,OR,97035,"825 Adams St, Portland, OR 97035"
182472,299125,USB-C Charging Cable,1,11.95,2020-01-01 04:21:00,754 Hickory St,New York City,NY,10001,"754 Hickory St, New York City, NY 10001"
182473,305840,Bose SoundSport Headphones,1,99.99,2020-01-01 04:54:00,784 River St,San Francisco,CA,94016,"784 River St, San Francisco, CA 94016"
182474,300519,Lightning Charging Cable,1,14.95,2020-01-01 05:13:00,657 Spruce St,New York City,NY,10001,"657 Spruce St, New York City, NY 10001"
182475,300519,Bose SoundSport Headphones,1,99.99,2020-01-01 05:13:00,657 Spruce St,New York City,NY,10001,"657 Spruce St, New York City, NY 10001"

In [207]:
df.groupby(['City']).sum()[['Quantity Ordered','Price Each']].sort_values('Price Each',ascending=False)

               Quantity Ordered    Price Each
City
San Francisco             49295  8.066747e+06
Los Angeles               32681  5.321352e+06
New York City             27442  4.550840e+06
Boston                    22089  3.577064e+06
Atlanta                   16286  2.724948e+06
Dallas                    16430  2.700018e+06
Seattle                   16262  2.676162e+06
Portland                  13791  2.263436e+06
Austin                    10917  1.775698e+06

# Task 4: Categorize Product

In [209]:
# Check all category
df['Category_check'] = df['Product'].str.contains('Headphones|Charging Cable|Batteries|Monitor|Laptop|Phone|TV|Dryer|Washing Machine',regex=True)

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [210]:
df[df['Category_check']==False]

Empty DataFrame
Columns: [Order ID, Product, Quantity Ordered, Price Each, Order Date, Street, City, State, post_id, Purchase Address, Category_check]
Index: []

In [211]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Street,City,State,post_id,Purchase Address,Category_check
0,147268,Wired Headphones,1,11.99,2019-01-01 03:07:00,9 Lake St,New York City,NY,10001,"9 Lake St, New York City, NY 10001",True
1,148041,USB-C Charging Cable,1,11.95,2019-01-01 03:40:00,760 Church St,San Francisco,CA,94016,"760 Church St, San Francisco, CA 94016",True
2,149343,Apple Airpods Headphones,1,150.00,2019-01-01 04:56:00,735 5th St,New York City,NY,10001,"735 5th St, New York City, NY 10001",True
3,149964,AAA Batteries (4-pack),1,2.99,2019-01-01 05:53:00,75 Jackson St,Dallas,TX,75001,"75 Jackson St, Dallas, TX 75001",True
4,149350,USB-C Charging Cable,2,11.95,2019-01-01 06:03:00,943 2nd St,Atlanta,GA,30301,"943 2nd St, Atlanta, GA 30301",True

In [212]:
Category = ['Headphones','Charging Cable','Batteries','Monitor','Laptop','Phone','TV','Dryer','Washing Machine']
def product_categorize(txt):
    for cate in Category:
        if cate in txt:
            return cate
df['Product Category'] = df['Product'].apply(product_categorize)

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [217]:
del df['Category_check']

In [218]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Street,City,State,post_id,Purchase Address,Product Category,Month,Month_name
0,147268,Wired Headphones,1,11.99,2019-01-01 03:07:00,9 Lake St,New York City,NY,10001,"9 Lake St, New York City, NY 10001",Headphones,2019-01,January
1,148041,USB-C Charging Cable,1,11.95,2019-01-01 03:40:00,760 Church St,San Francisco,CA,94016,"760 Church St, San Francisco, CA 94016",Charging Cable,2019-01,January
2,149343,Apple Airpods Headphones,1,150.00,2019-01-01 04:56:00,735 5th St,New York City,NY,10001,"735 5th St, New York City, NY 10001",Headphones,2019-01,January
3,149964,AAA Batteries (4-pack),1,2.99,2019-01-01 05:53:00,75 Jackson St,Dallas,TX,75001,"75 Jackson St, Dallas, TX 75001",Batteries,2019-01,January
4,149350,USB-C Charging Cable,2,11.95,2019-01-01 06:03:00,943 2nd St,Atlanta,GA,30301,"943 2nd St, Atlanta, GA 30301",Charging Cable,2019-01,January

In [219]:
df['Month'] = df['Order Date'].dt.to_period('M')

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [220]:
df['Month_name'] = df['Order Date'].dt.month_name()

C:\Users\Asus\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [221]:
df.columns
df = df[['Order ID', 'Product','Product Category' ,'Quantity Ordered', 'Price Each', 'Order Date','Month_name','Month',
       'Street', 'City', 'State', 'post_id', 'Purchase Address']]
df.head()

,Order ID,Product,Product Category,Quantity Ordered,Price Each,Order Date,Month_name,Month,Street,City,State,post_id,Purchase Address
0,147268,Wired Headphones,Headphones,1,11.99,2019-01-01 03:07:00,January,2019-01,9 Lake St,New York City,NY,10001,"9 Lake St, New York City, NY 10001"
1,148041,USB-C Charging Cable,Charging Cable,1,11.95,2019-01-01 03:40:00,January,2019-01,760 Church St,San Francisco,CA,94016,"760 Church St, San Francisco, CA 94016"
2,149343,Apple Airpods Headphones,Headphones,1,150.00,2019-01-01 04:56:00,January,2019-01,735 5th St,New York City,NY,10001,"735 5th St, New York City, NY 10001"
3,149964,AAA Batteries (4-pack),Batteries,1,2.99,2019-01-01 05:53:00,January,2019-01,75 Jackson St,Dallas,TX,75001,"75 Jackson St, Dallas, TX 75001"
4,149350,USB-C Charging Cable,Charging Cable,2,11.95,2019-01-01 06:03:00,January,2019-01,943 2nd St,Atlanta,GA,30301,"943 2nd St, Atlanta, GA 30301"

In [222]:
df.to_csv('sale_analysis_modified.csv')

In [223]:
df[df['Month']== '2020-01']

,Order ID,Product,Product Category,Quantity Ordered,Price Each,Order Date,Month_name,Month,Street,City,State,post_id,Purchase Address
182442,311386,Apple Airpods Headphones,Headphones,1,150.00,2020-01-01 00:10:00,January,2020-01,730 Pine St,San Francisco,CA,94016,"730 Pine St, San Francisco, CA 94016"
182443,311386,iPhone,Phone,1,700.00,2020-01-01 00:10:00,January,2020-01,730 Pine St,San Francisco,CA,94016,"730 Pine St, San Francisco, CA 94016"
182444,300759,20in Monitor,Monitor,1,109.99,2020-01-01 00:14:00,January,2020-01,193 5th St,Austin,TX,73301,"193 5th St, Austin, TX 73301"
182445,302393,Lightning Charging Cable,Charging Cable,1,14.95,2020-01-01 00:14:00,January,2020-01,108 Jefferson St,Boston,MA,02215,"108 Jefferson St, Boston, MA 02215"
182446,297817,Lightning Charging Cable,Charging Cable,2,14.95,2020-01-01 00:22:00,January,2020-01,519 13th St,New York City,NY,10001,"519 13th St, New York City, NY 10001"
182447,297817,iPhone,Phone,1,700.00,2020-01-01 00:22:00,January,2020-01,519 13th St,New York City,NY,10001,"519 13th St, New York City, NY 10001"
182448,308322,Bose SoundSport Headphones,Headphones,1,99.99,2020-01-01 00:24:00,January,2020-01,362 Willow St,San Francisco,CA,94016,"362 Willow St, San Francisco, CA 94016"
182449,297150,Lightning Charging Cable,Charging Cable,1,14.95,2020-01-01 00:38:00,January,2020-01,427 Wilson St,Dallas,TX,75001,"427 Wilson St, Dallas, TX 75001"
182450,319366,20in Monitor,Monitor,2,109.99,2020-01-01 00:45:00,January,2020-01,746 South St,San Francisco,CA,94016,"746 South St, San Francisco, CA 94016"
182451,315138,AAA Batteries (4-pack),Batteries,3,2.99,2020-01-01 00:51:00,January,2020-01,257 Adams St,New York City,NY,10001,"257 Adams St, New York City, NY 10001"
182452,297969,Google Phone,Phone,1,600.00,2020-01-01 00:54:00,January,2020-01,542 2nd St,San Francisco,CA,94016,"542 2nd St, San Francisco, CA 94016"
182453,300362,USB-C Charging Cable,Charging Cable,1,11.95,2020-01-01 00:59:00,January,2020-01,581 River St,San Francisco,CA,94016,"581 River St, San Francisco, CA 94016"
182454,305538,Apple Airpods Headphones,Headphones,1,150.00,2020-01-01 01:00:00,January,2020-01,693 1st St,Portland,OR,97035,"693 1st St, Portland, OR 97035"
182455,316867,27in FHD Monitor,Monitor,1,149.99,2020-01-01 01:05:00,January,2020-01,137 Madison St,Seattle,WA,98101,"137 Madison St, Seattle, WA 98101"
182456,299049,Apple Airpods Headphones,Headphones,1,150.00,2020-01-01 01:17:00,January,2020-01,762 Johnson St,San Francisco,CA,94016,"762 Johnson St, San Francisco, CA 94016"
182457,315315,27in 4K Gaming Monitor,Monitor,1,389.99,2020-01-01 01:22:00,January,2020-01,552 North St,Austin,TX,73301,"552 North St, Austin, TX 73301"
182458,310074,Apple Airpods Headphones,Headphones,1,150.00,2020-01-01 01:46:00,January,2020-01,636 Lakeview St,San Francisco,CA,94016,"636 Lakeview St, San Francisco, CA 94016"
182459,306655,ThinkPad Laptop,Laptop,1,999.99,2020-01-01 01:46:00,January,2020-01,431 Hickory St,Los Angeles,CA,90001,"431 Hickory St, Los Angeles, CA 90001"
182460,314552,AAA Batteries (4-pack),Batteries,1,2.99,2020-01-01 01:47:00,January,2020-01,541 4th St,San Francisco,CA,94016,"541 4th St, San Francisco, CA 94016"
182461,314066,USB-C Charging Cable,Charging Cable,1,11.95,2020-01-01 01:52:00,January,2020-01,922 8th St,New York City,NY,10001,"922 8th St, New York City, NY 10001"
182462,312812,Flatscreen TV,TV,1,300.00,2020-01-01 01:56:00,January,2020-01,129 6th St,Boston,MA,02215,"129 6th St, Boston, MA 02215"
182463,307890,Lightning Charging Cable,Charging Cable,1,14.95,2020-01-01 02:06:00,January,2020-01,39 Pine St,New York City,NY,10001,"39 Pine St, New York City, NY 10001"
182464,312012,27in FHD Monitor,Monitor,1,149.99,2020-01-01 02:12:00,January,2020-01,507 13th St,San Francisco,CA,94016,"507 13th St, San Francisco, CA 94016"
182465,306809,Macbook Pro Laptop,Laptop,1,1700.00,2020-01-01 02:20:00,January,2020-01,326 14th St,Dallas,TX,75001,"326 14th St, Dallas, TX 75001"
182466,316833,Vareebadd Phone,Phone,1,400.00,2020-01-01 02:58:00,January,2020-01,378 Elm St,New York City,NY,10001,"378 Elm St, New York City, NY 10001"
182467,319308,USB-C Charging Cable,Charging Cable,1,11.95,2020-01-01 03:13:00,January,2020-01,135 8th St,Boston,MA,02215,"135 8th St, Boston, MA 02215"
182468,306928,ThinkPad Laptop,Laptop,1,999.99,2020-01-01 03:14:00,January,2020-01,762 Elm St,Boston,MA,02215,"762 Elm St, Boston, MA 02215"
182469,298344,Wired Headphones,Headphones,4,11.99,2020-01-01 03:34:00,January,2020-01,731 7th St,New York City,NY,10001,"731 7th St, New York City, NY 10001"
182470,308185,27in FHD Monitor,Monitor,1,149.99,2020-01-01 04:06:00,January,2020-01,202 Maple St,San Francisco,CA,94016,"202 Maple St, San Francisco, CA 94016"
182471,304165,AAA Batteries (4-pack),Batteries,1,2.99,2020-01-01 04:13:00,January,2020-01,825 Adams St,Portland,OR,97035,"825 Adams St, Portland, OR 97035"
182472,299125,USB-C Charging Cable,Charging Cable,1,11.95,2020-01-01 04:21:00,January,2020-01,754 Hickory St,New York City,NY,10001,"754 Hickory St, New York City, NY 10001"
182473,305840,Bose SoundSport Headphones,Headphones,1,99.99,2020-01-01 04:54:00,January,2020-01,784 River St,San Francisco,CA,94016,"784 River St, San Francisco, CA 94016"
182474,300519,Lightning Charging Cable,Charging Cable,1,14.95,2020-01-01 05:13:00,January,2020-01,657 Spruce St,New York City,NY,10001,"657 Spruce St, New York City, NY 10001"
182475,300519,Bose SoundSport Headphones,Headphones,1,99.99,2020-01-01 05:13:00,January,2020-01,657 Spruce St,New York City,NY,10001,"657 Spruce St, New York City, NY 10001"